### ISSUE TITLE
[koffi] Reducing size of binary/npm package

### ISSUE THREAD

**Issue by Septh** [Koromix/rygel#84] opened 2024-10-28 15:55 UTC
Hi,

I'm using Koffi to build [libwin32](https://github.com/Septh/libwin32) and so far everything is working fine -Koffi makes this a breeze, many thanks for the great work!

My only concern is about the size of the Koffi binary: 2.23Mb for the win32-x64 binary alone seems quite a lot considering the code base is rather small. While I successfully built Koffi from sources, I have very little knowledge of the C++ build tools and I couldn't find a way to get a lighter binary. Would you have any advice here?

Also, would you consider exploring the possibility to publish multiple npm packages -one per platform/arch build- instead of a single, monolithic package? This would save bandwidth and time to users. [Rollup](https://github.com/rollup/rollup) and [esbuild](https://github.com/evanw/esbuild) are two examples of popular npm packages with native code distributed this way:

https://www.npmjs.com/package/@rollup/rollup-linux-x64-gnu
https://www.npmjs.com/package/@rollup/rollup-win32-x64-msvc
etc.

Thanks!

**Comment by Koromix** [comment] 2024-10-28 17:35
Hi,

So, with regards to the binary size, most of it is caused by the static trampolines. For callbacks, Koffi uses a set of 8192 predefined trampolines, which means that there is a prebaked, autogenerated and mostly-repeated (8192 times) set of assembly instructions.

You can see it here for `System V x86_64 ABI`: https://github.com/Koromix/rygel/blob/master/src/koffi/src/trampolines/gnu.inc

This accounts for almost all of the binary size ;) I just built a stripped down Koffi build on Linux x86_64 with

- 8192 trampolines: koffi.node is 4.4M
- 4096 trampolines: koffi.node is 2.5M
- 1024 trampolines: koffi.node is 1.1M

I guess I could reduce the number of baked trampolines to 4096, in Koffi 3.0, to reduce binary size.

**Comment by Koromix** [comment] 2024-10-28 17:40
For the second point, I think the simplicity of including all pre-built binaries in one package trump all other considerations, especially for users who want to vendor all dependencies.

Which, if I'm honest, includes me; just look at the `vendor/` directory of this repository if you want to find out how I manage dependencies. Also, look at the README section about my C++ coding style: https://github.com/Koromix/rygel/tree/master?tab=readme-ov-file#c-flavor

**Comment by Septh** [comment] 2024-10-29 19:22
> I guess I could reduce the number of baked trampolines to 4096, in Koffi 3.0, to reduce overall binary size.

TBH, I am not familiar with the concept of _trampoline_ and had to google a bit to find out. If I understand correctly, they are more or less jump tables used to translate Koffi's idea of a prototype with the actual ABI of the loaded library. Therefore, Koffi needs to reserve one trampoline per call to `lib.func`.

If I'm right, then 8192 trampolines is definitely oversized and even 4096 seems like too many. I'm not sure what a good number would be but I guess it'd be somewhere in the 1024-2048 range.

> For the second point, I think the simplicity of including all pre-built binaries in one package trumps all other considerations, especially for users who want to vendor all dependencies.

I respectfully disagree. 😁 You can't use the `linux-arm64` build on a Mac, you can't use `darwin-x64` build on Windows, and you can't use the `win32_ia32` build on Linux. Each build is tied to exactly one platform and useless on the others. Hence, having the user download 75Mb of code of which he only really needs 3 or 4 Mb seems like a waste.

Why not provide both the monolithic hulk **and** individual packages? This could easily be automated on CI. What do you think?

**Comment by Koromix** [comment] 2024-10-29 21:03
I understand your point of view regarding Koffi binaries However, I won't change how it works because I much prefer things this way.

I think putting everything in one package is better, because:

* It is self-contained, you can copy the koffi package directory around/on other platforms/put a copy in your own repo/wherever and it works regardless of the platform.
* Package updates are atomic, there is less risk of version mismatch between the main library and the "binary" package.
* It is less work for me to handle. I don't like Cloud CI, I use qemu to test and package Koffi for different platforms, and I run everything on my local machine.
* It makes vendoring whole package easier. I don't like to depend on the internet when I work on my code. Which means package managers are out. When I work on a project, I want to clone ONE repository and be done with any need for internet access.

I strongly disagree with the NPM/Cargo/whatever way of doing things where everything depends on many things. The only reason I distribute Koffi on NPM is because that's what's expected for Node.js libraries. I'd be just as happy (well, happier) if ZIPs or tarballs where preferred.

As you can see, Koffi depends on nothing that is outside of the Koromix/rygel monorepo (except for the code for benchmarks, which pulls node-ffi-napi, among others).

When you redistribute your code, you are free to remove the parts of Koffi that you don't want, such as extra binaries.

**Comment by Koromix** [comment] 2024-10-29 21:10
Hey, just found out that Koffi was using NPM esbuild to make the NPM package, even though I have a copy of esbuild in the repository (in `vendor/esbuild/`).

Well, I'm glad I checked, it's fixed now.

**Comment by Koromix** [comment] 2024-10-29 21:30
Also, regarding bandwith: there Koffi binaries compress well (in part due to the fact that a lot of it is highly-repeated / low-entropy code), and `koffi-2.9.1.tgz` weighs around 15M.

**Comment by Septh** [comment] 2024-10-30 00:40
> Trampolines are used for Javascript callbacks. When you pass a JS function to a C function that expects a callback. So, they are used for C to JS calls. They are not used for simple JS to C calls.

I see. Thanks for the clarification.

> There is another way to reduce binary size: stripping out debug info, which accounts for half the binary size.

Yup, that was my first thought before I decided to file the issue. I'll have to find the right compiler switches but that is something I should be able to manage :)

> I strongly disagree with the NPM/Cargo/whatever way of doing things where everything depends on many things. The only reason I distribute Koffi on NPM is because that's what's expected for Node.js libraries. I'd be just as happy (well, happier) if ZIPs or tarballs were preferred.

This too is highly debatable 😄  But I don't think this is the right place so I'll just respect your decision and see what I can get by myself. 

Thank you again for this otherwise excellent package! ;)

**Comment by Koromix** [comment] 2024-10-30 07:44
I just tried making a build without debug symbols, and the final package weighted 67M (13M compressed).

I won't strip debug symbols from the official package because it might make it much harder for me to debug future bug reports, for a relatively small size gain.

**Closed** 2024-10-30 09:05 UTC
